### ISSUE TITLE
TODO: Database收集数据、chrome extension进行抽奖

### ISSUE THREAD

**Issue by Billyzou0741326** [Billyzou0741326/bilibili-live-monitor-js#18]
最近发现学校提供MySQL数据库 不利用一下有些说不过去呢... 
Python版的抽奖端感觉填写设置有些复杂了 如果用chrome插件实现的话就可以避免输入用户数据（直接由chrome读取cookies）
- [x] MySQL 
- [ ] ~~多线程（处理器）分担监控~~
- [ ] ~~Chrome Extension 抽奖端~~
- [ ] NodeJS 抽奖端（总决赛前实现(不了)）

又发现学校提供对外网开放的服务器了... 如果不打算自己建服务器的话 我这边也是可以提供推送的

**Comment by Billyzou0741326** [comment]
认真考虑了一下 发现这个项目多加新功能是不太合适的
功能多了不利于维护，后期作出的所有修改都要顾及到对原有功能的影响
新功能全部用单独的repository吧 功能单一的项目很容易debug和维护

数据库其实不用跟高能播报的逻辑放在一起的。既然是内网推送，延迟应该是极低的（根本不通过网络传递数据），通过127.0.0.1接收信息然后存入数据库也是非常快的。因此把逻辑分开不会造成什么影响
麻烦的是 我数据库知识几乎是0 所以只能实力划水了23333

chrome插件的设计不太确定... 毕竟Python版的client还能继续用，优先级放到最低

**Comment by Billyzou0741326** [comment]
```
+------------+-------------+------+-----+---------+-------+
| Field      | Type        | Null | Key | Default | Extra |
+------------+-------------+------+-----+---------+-------+
| id         | int(11)     | NO   | PRI | NULL    |       |
| roomid     | bigint(20)  | NO   |     | NULL    |       |
| type       | varchar(20) | NO   |     | NULL    |       |
| name       | varchar(30) | NO   |     | NULL    |       |
| created_at | datetime    | YES  |     | NULL    |       |
+------------+-------------+------+-----+---------+-------+
```

```
+---------+----------+-------+--------+---------------------+
| id      | roomid   | type  | name   | created_at          |
+---------+----------+-------+--------+---------------------+
| 1693862 | 21387411 | guard | 舰长   | 2019-11-28 11:00:11 |
+---------+----------+-------+--------+---------------------+
```
大概这种格式吧

**Comment by Billyzou0741326** [comment]
```mysql
SELECT roomid, COUNT(id) as count 
FROM live
WHERE type='guard' 
AND created_at>DATE(CURRENT_DATE() - 1)
GROUP BY roomid
HAVING count>10;
```
获取前一天检测到的上船数最高的房间（并非真实上船数）

**Comment by lovezm** [comment]
对了你可以用tcp连接弹幕服务器 
参考这个项目 https://github.com/simon300000/bilibili-live-ws
效率比ws高 应该会减少漏的问题吧

**Comment by lovezm** [comment]
你把监听完善 我去写chrome插件吧 23333

**Comment by Billyzou0741326** [comment]
> 你把监听完善 我去写chrome插件吧 23333

> 对了你可以用tcp连接弹幕服务器
> 参考这个项目` https://github.com/simon300000/bilibili-live-ws
> 效率比ws高 应该会减少漏的问题吧

谢谢大佬指点，刚刚粗略看了下那个项目的完善度极高呢... 有时间仔细看下
我这边尽力完善吧（不太确定有没有达到稳定的可能性23333）
Chrome插件我至今没动hhh如果可以写的话就帮大忙了

不过TCP连接我已经在用了好像
https://github.com/Billyzou0741326/bilibili-live-monitor-js/blob/4763ca3e00fdfdaa9fc763db7011cc8abf66fef4/src/danmu/bilibilisocket.js#L58-L61
https://github.com/Billyzou0741326/bilibili-live-monitor-js/blob/4763ca3e00fdfdaa9fc763db7011cc8abf66fef4/src/global/config.js#L7-L10

感谢大佬 这个瓶颈再卡下去我就要绝望了23333

**Comment by Billyzou0741326** [comment]
> 你把监听完善 我去写chrome插件吧 23333

想了下插件端可能会比较麻烦... 如果没时间的话也没关系 我慢慢划水也可以的23333

**Comment by Billyzou0741326** [comment]
最新覆盖率 （满意了）

| id      | roomid   | type  | name   | created_at          |
|---------|----------|-------|--------|---------------------|
| 1733139 | 21297516 | guard | 舰长   | 2019-12-07 11:57:44 |
| 1733140 | 21297516 | guard | 提督   | 2019-12-07 11:57:54 |
| 1733141 | 21539718 | guard | 舰长   | 2019-12-07 11:59:49 |
| 1733142 |  6806787 | guard | 舰长   | 2019-12-07 12:04:09 |
| 1733143 |  6806787 | guard | 舰长   | 2019-12-07 12:04:09 |
| 1733144 |  6806787 | guard | 舰长   | 2019-12-07 12:04:09 |
| 1733145 | 21297516 | guard | 舰长   | 2019-12-07 12:07:14 |
| 1733146 | 21297516 | guard | 舰长   | 2019-12-07 12:08:04 |
| 1733147 | 21669084 | guard | 舰长   | 2019-12-07 12:08:19 |
| 1733148 |    10168 | guard | 舰长   | 2019-12-07 12:12:39 |
| 1733150 |  2296870 | guard | 舰长   | 2019-12-07 12:16:49 |
| 1733152 |    66688 | guard | 舰长   | 2019-12-07 12:27:39 |
| 1733153 | 21395965 | guard | 舰长   | 2019-12-07 12:29:59 |
| 1733154 | 21143742 | guard | 舰长   | 2019-12-07 12:37:22 |
| 1733157 | 21596782 | guard | 舰长   | 2019-12-07 12:46:42 |
| 1733158 |   982077 | guard | 舰长   | 2019-12-07 12:48:22 |
| 1733159 | 21708625 | guard | 舰长   | 2019-12-07 12:48:37 |
| 1733160 | 21224291 | guard | 舰长   | 2019-12-07 12:51:47 |
| 1733161 |  3313141 | guard | 舰长   | 2019-12-07 12:52:07 |
| 1733162 | 13200846 | guard | 舰长   | 2019-12-07 12:54:12 |
| 1733163 | 21224291 | guard | 提督   | 2019-12-07 12:55:32 |
| 1733164 |  6079245 | guard | 舰长   | 2019-12-07 12:56:07 |
| 1733165 | 21224291 | guard | 舰长   | 2019-12-07 12:57:32 |
| 1733166 | 21224291 | guard | 舰长   | 2019-12-07 12:59:52 |
| 1733169 |  6806787 | guard | 提督   | 2019-12-07 13:13:37 |
| 1733170 |  2802503 | guard | 舰长   | 2019-12-07 13:19:07 |
| 1733171 | 21540083 | guard | 舰长   | 2019-12-07 13:21:02 |
| 1733172 | 21708625 | guard | 舰长   | 2019-12-07 13:23:27 |
| 1733173 | 12885331 | guard | 舰长   | 2019-12-07 13:23:27 |
| 1733174 | 21148783 | guard | 舰长   | 2019-12-07 13:26:22 |
| 1733175 |   982077 | guard | 舰长   | 2019-12-07 13:27:57 |
| 1733176 |   982077 | guard | 舰长   | 2019-12-07 13:29:52 |
| 1733177 |  5064045 | guard | 舰长   | 2019-12-07 13:31:57 |
| 1733178 |    10116 | guard | 舰长   | 2019-12-07 13:38:47 |
| 1733179 |  7603080 | guard | 舰长   | 2019-12-07 13:39:12 |
| 1733180 | 10556121 | guard | 舰长   | 2019-12-07 13:40:17 |
| 1733181 | 10556121 | guard | 舰长   | 2019-12-07 13:40:37 |
| 1733182 |    75031 | guard | 舰长   | 2019-12-07 13:41:17 |
| 1733183 |  3919985 | guard | 舰长   | 2019-12-07 13:47:07 |
| 1733184 | 10618713 | guard | 舰长   | 2019-12-07 13:48:32 |

**Comment by Billyzou0741326** [comment]
> 最新覆盖率 （满意了）
> 
> id	roomid	type	name	created_at
> 1733139	21297516	guard	舰长	2019-12-07 11:57:44
> 1733140	21297516	guard	提督	2019-12-07 11:57:54
> 1733141	21539718	guard	舰长	2019-12-07 11:59:49
> 1733142	6806787	guard	舰长	2019-12-07 12:04:09
> 1733143	6806787	guard	舰长	2019-12-07 12:04:09
> 1733144	6806787	guard	舰长	2019-12-07 12:04:09
> 1733145	21297516	guard	舰长	2019-12-07 12:07:14
> 1733146	21297516	guard	舰长	2019-12-07 12:08:04
> 1733147	21669084	guard	舰长	2019-12-07 12:08:19
> 1733148	10168	guard	舰长	2019-12-07 12:12:39
> 1733150	2296870	guard	舰长	2019-12-07 12:16:49
> 1733152	66688	guard	舰长	2019-12-07 12:27:39
> 1733153	21395965	guard	舰长	2019-12-07 12:29:59
> 1733154	21143742	guard	舰长	2019-12-07 12:37:22
> 1733157	21596782	guard	舰长	2019-12-07 12:46:42
> 1733158	982077	guard	舰长	2019-12-07 12:48:22
> 1733159	21708625	guard	舰长	2019-12-07 12:48:37
> 1733160	21224291	guard	舰长	2019-12-07 12:51:47
> 1733161	3313141	guard	舰长	2019-12-07 12:52:07
> 1733162	13200846	guard	舰长	2019-12-07 12:54:12
> 1733163	21224291	guard	提督	2019-12-07 12:55:32
> 1733164	6079245	guard	舰长	2019-12-07 12:56:07
> 1733165	21224291	guard	舰长	2019-12-07 12:57:32
> 1733166	21224291	guard	舰长	2019-12-07 12:59:52
> 1733169	6806787	guard	提督	2019-12-07 13:13:37
> 1733170	2802503	guard	舰长	2019-12-07 13:19:07
> 1733171	21540083	guard	舰长	2019-12-07 13:21:02
> 1733172	21708625	guard	舰长	2019-12-07 13:23:27
> 1733173	12885331	guard	舰长	2019-12-07 13:23:27
> 1733174	21148783	guard	舰长	2019-12-07 13:26:22
> 1733175	982077	guard	舰长	2019-12-07 13:27:57
> 1733176	982077	guard	舰长	2019-12-07 13:29:52
> 1733177	5064045	guard	舰长	2019-12-07 13:31:57
> 1733178	10116	guard	舰长	2019-12-07 13:38:47
> 1733179	7603080	guard	舰长	2019-12-07 13:39:12
> 1733180	10556121	guard	舰长	2019-12-07 13:40:17
> 1733181	10556121	guard	舰长	2019-12-07 13:40:37
> 1733182	75031	guard	舰长	2019-12-07 13:41:17
> 1733183	3919985	guard	舰长	2019-12-07 13:47:07
> 1733184	10618713	guard	舰长	2019-12-07 13:48:32

程序运行越久覆盖率越高（应该吧）

**Comment by lovezm** [comment]
哇 真就不睡觉

**Comment by lovezm** [comment]
这覆盖率很高了 没漏多少

发送自 Windows 10 版邮件应用

发件人: kotoriのねこ
发送时间: 2019年12月8日 6:07
收件人: Billyzou0741326/bilibili-live-monitor-js
抄送: WangMuDu; Comment
主题: Re: [Billyzou0741326/bilibili-live-monitor-js] TODO: Database收集数据、chrome extension进行抽奖 (#18)

最新覆盖率 （满意了）
id roomid type name created_at
1733139 21297516 guard 舰长 2019-12-07 11:57:44
1733140 21297516 guard 提督 2019-12-07 11:57:54
1733141 21539718 guard 舰长 2019-12-07 11:59:49
1733142 6806787 guard 舰长 2019-12-07 12:04:09
1733143 6806787 guard 舰长 2019-12-07 12:04:09
1733144 6806787 guard 舰长 2019-12-07 12:04:09
1733145 21297516 guard 舰长 2019-12-07 12:07:14
1733146 21297516 guard 舰长 2019-12-07 12:08:04
1733147 21669084 guard 舰长 2019-12-07 12:08:19
1733148 10168 guard 舰长 2019-12-07 12:12:39
1733150 2296870 guard 舰长 2019-12-07 12:16:49
1733152 66688 guard 舰长 2019-12-07 12:27:39
1733153 21395965 guard 舰长 2019-12-07 12:29:59
1733154 21143742 guard 舰长 2019-12-07 12:37:22
1733157 21596782 guard 舰长 2019-12-07 12:46:42
1733158 982077 guard 舰长 2019-12-07 12:48:22
1733159 21708625 guard 舰长 2019-12-07 12:48:37
1733160 21224291 guard 舰长 2019-12-07 12:51:47
1733161 3313141 guard 舰长 2019-12-07 12:52:07
1733162 13200846 guard 舰长 2019-12-07 12:54:12
1733163 21224291 guard 提督 2019-12-07 12:55:32
1733164 6079245 guard 舰长 2019-12-07 12:56:07
1733165 21224291 guard 舰长 2019-12-07 12:57:32
1733166 21224291 guard 舰长 2019-12-07 12:59:52
1733169 6806787 guard 提督 2019-12-07 13:13:37
1733170 2802503 guard 舰长 2019-12-07 13:19:07
1733171 21540083 guard 舰长 2019-12-07 13:21:02
1733172 21708625 guard 舰长 2019-12-07 13:23:27
1733173 12885331 guard 舰长 2019-12-07 13:23:27
1733174 21148783 guard 舰长 2019-12-07 13:26:22
1733175 982077 guard 舰长 2019-12-07 13:27:57
1733176 982077 guard 舰长 2019-12-07 13:29:52
1733177 5064045 guard 舰长 2019-12-07 13:31:57
1733178 10116 guard 舰长 2019-12-07 13:38:47
1733179 7603080 guard 舰长 2019-12-07 13:39:12
1733180 10556121 guard 舰长 2019-12-07 13:40:17
1733181 10556121 guard 舰长 2019-12-07 13:40:37
1733182 75031 guard 舰长 2019-12-07 13:41:17
1733183 3919985 guard 舰长 2019-12-07 13:47:07
1733184 10618713 guard 舰长 2019-12-07 13:48:32
程序运行越久覆盖率越高（应该吧）

**Comment by Billyzou0741326** [comment]
> 哇 真就不睡觉

是要睡的hhh毕竟不是铁人
不过时差....

**Comment by Billyzou0741326** [comment]
> 这覆盖率很高了 没漏多少 

这个版本还没发出来... 正在测试

**Comment by lovezm** [comment]
看到了 2333

发送自 Windows 10 版邮件应用

**Comment by lovezm** [comment]
我想用e写一个桌面版的  UI看点些 但是苦恼 e的websocket方面知识太少了 =。=

发送自 Windows 10 版邮件应用

发件人: kotoriのねこ
发送时间: 2019年12月8日 7:03
收件人: Billyzou0741326/bilibili-live-monitor-js
抄送: WangMuDu; Comment
主题: Re: [Billyzou0741326/bilibili-live-monitor-js] TODO: Database收集数据、chrome extension进行抽奖 (#18)

这覆盖率很高了 没漏多少
这个版本还没发出来... 正在测试

**Comment by Billyzou0741326** [comment]
> 我想用e写一个桌面版的 UI看点些 但是苦恼 e的websocket方面知识太少了 =。= 

没事啊2333

合作吧 websocket连接服务器的逻辑我可以写的 
过几天放假了，有不少想法可以实现

**Comment by lovezm** [comment]
可以！只要能接收到服务端的消息就好  分开写客户端也方便维护 加个tg？https://t.me/helloergou

发送自 Windows 10 版邮件应用

发件人: kotoriのねこ
发送时间: 2019年12月8日 7:16
收件人: Billyzou0741326/bilibili-live-monitor-js
抄送: WangMuDu; Comment
主题: Re: [Billyzou0741326/bilibili-live-monitor-js] TODO: Database收集数据、chrome extension进行抽奖 (#18)

我想用e写一个桌面版的 UI看点些 但是苦恼 e的websocket方面知识太少了 =。=
没事啊2333
合作吧 websocket连接服务器的逻辑我可以写的
过几天放假了，有不少想法可以实现

**Comment by Billyzou0741326** [comment]
> 可以！只要能接收到服务端的消息就好 分开写客户端也方便维护 加个tg？https://t.me/helloergou 

我得下载和注册下2333

**Comment by lovezm** [comment]
-.-
比如说我用http://www.easyswoole.com/wstool.html测试
Ws://127.0.0.1:8999
我在这个测试端 咋握手啊 咋ping啊 咋…（萌新三连

发送自 Windows 10 版邮件应用

发件人: kotoriのねこ
发送时间: 2019年12月8日 7:27
收件人: Billyzou0741326/bilibili-live-monitor-js
抄送: WangMuDu; Comment
主题: Re: [Billyzou0741326/bilibili-live-monitor-js] TODO: Database收集数据、chrome extension进行抽奖 (#18)

可以！只要能接收到服务端的消息就好 分开写客户端也方便维护 加个tg？https://t.me/helloergou
我得下载和注册下2333

**Comment by Billyzou0741326** [comment]
```mysql
SELECT roomid, COUNT(id) as count  
FROM bilibili.live 
WHERE type='guard' 
AND created_at>DATE(CURRENT_DATE() - 1) 
GROUP BY roomid 
HAVING count>10 
ORDER BY count DESC;
```
@lovezm 二狗大佬试试用这个command   查昨天+今天检测到的上舰数量的
这样应该不用特意存热门了
